### PR TITLE
Support for log4j2

### PR DESCRIPTION
**Pull request by fireandfuel**
Added support for log4j2 because log4j 1.X is EOL since August 5, 2015

### CODE REVIEW

**Comment by swaldman** [comment]
hi,

i just want to apologize, really a lot, that i haven't had time to take a good look at this. adding log4j2 support is really kind. it's been a very busy time, but i didn't expect it would take so long. i will get back to you on this soon.

thank you again, and big apologies again for flaking.

**Comment by JanYunkai** [comment]
what about this project

**Comment by JanYunkai** [comment]
what`s about this project

**Comment by swaldman** [comment]
@fireandfuel @JunYunkai My apologies for letting this languish for so long.

@fireandfuel This looks great, I'm inclined to merge it. But in lieu of a formal CLA, can I ask your permission too 1) include and redistribute this under the existing choice of licenses; and 2) relicense the contribution on alternative terms as I see fit?

I don't love asking for (2), but not having that permission was a hassle when the library migrated from LGPL alone to choice of LGPL or EPL. In general, any relicensing would probably be to some alternative open source license, but I also use these libraries in consulting work and it's not inconceivable, although it has never actually happened, that some client would ask for a nonexclusive license on custom terms.

I'm really sorry again for the now very long flake. I'm working on other things recently, and it is too easy to put things off. I really do appreciate the effort you put in to understand my unruly code, and to modernize its functionality. You deserve better than to be long ignored.

**Comment by swaldman** [comment]
@JanYunkai Thanks for prodding me on this. I appreciate it.

**Comment by fireandfuel** [comment]
@swaldman I give you my permission for 1) and 2)

**Comment by swaldman** [comment]
@fireandfuel Thanks! And for your work. And for your patience.

**Pull request merged**
